SoundEffects:
  - soundCode: 0
    path: resources/sounds/step1.wav
    volume: 50
  - soundCode: 1
    path: resources/sounds/jump.wav
    volume: 20
  - soundCode: 2
    path: resources/sounds/gun.mp3
    volume: 50

Music:
  - songCode: 0
    path: resources/sounds/outrun_the_reaper.mp3