Chell:
  - name: RestingIdle
    path: resources/Chell/RestingIdle.png
    frames: 7
    width: 1
    height: 2
  - name: Jumping
    path: resources/Chell/Jumping.png
    frames: 4
    width: 1.25
    height: 2.15
  - name: Death
    path: resources/Chell/Death.png
    frames: 14
    width: 2
    height: 2.15
  - name: Win
    path: resources/Chell/WinRelief.png
    frames: 13
    width: 1
    height: 1.95
  - name: Run
    path: resources/Chell/Run.png
    frames: 12
    width: 2
    height: 1.95

BluePortal: {path: resources/portal/BluePortal.png, frames: 5}

OrangePortal: {path: resources/portal/OrangePortal.png, frames: 5}

EnergyBall: {path: resources/EnergyBall/energy-ball.png, frames: 4}

Acid: {path: resources/Acid/acid.png, frames: 8}

Bullet: {path: resources/Bullet/bullet.png, frames: 3}

Rock: {path: resources/rocks/1.png}

EnergyBar: {path: resources/energy-bar/vertical.png}

Gate: {path: resources/Gate/GateAnimated.png, frames: 19}

Button:
  - name: 1
    path: resources/button/on.png
  - name: 0
    path: resources/button/off.png

Cake: {path: resources/cake/initial.png, frames: 8}

StaticObjects:
  - name: MetalBlock
    path: resources/blocks/metal-block.png
  - name: RockBlock
    path: resources/blocks/rock-block.png
  - name: Button
    path: resources/button/off.png
  - name: LounchBlockDown
    path: resources/lounch-block/down.png
  - name: LounchBlockUp
    path: resources/lounch-block/up.png
  - name: LounchBlockLeft
    path: resources/lounch-block/left.png
  - name: LounchBlockRight
    path: resources/lounch-block/right.png
  - name: Rock1
    path: resources/rocks/1.png
  - name: Rock2
    path: resources/rocks/2.png
  - name: Rock3
    path: resources/rocks/3.png
