Chell:
  - name: RestingIdle
    path: resources/Chell/RestingIdle.png
    frames: 7
  - name: Run
    path: resources/Chell/Run.png
    frames: 12
  - name: Jumping
    path: resources/Chell/Jumping.png
    frames: 4

StaticObjects:
  - name: MetalBlock
    path: resources/blocks/switchblock.png
  - name: RockBlock
    path: resources/blocks/breakblock.png